permalink: \404.md
title: James Joseph Portfolio
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
domain: "jamesottoj.github.io"
url: "https://jamesottoj.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  jamesottoj

# Build settings
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
