permalink: \404.md
title: James Joseph Portfolio
description: >- # this means to ignore newlines until "baseurl:"
  Writups for my exploits in CTFs and other domains. I love reverse engineering and figuring out programs
baseurl: "" # the subpath of your site, e.g. /blog
domain: "jamesottoj.github.io"
url: "https://jamesottoj.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  jamesottoj

# Build settings
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
kramdown:
  hard_wrap: true
